
package hr.jkrizanic.sandbox.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T12:35:28.028+02:00
 * Generated source version: 2.7.5
 * 
 */
 
public class HelloPortType_HelloPortTypeBindingPort_Server{

    protected HelloPortType_HelloPortTypeBindingPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloPortTypeImpl();
        String address = "http://localhost:8080/HelloService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloPortType_HelloPortTypeBindingPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
