
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package hr.jkrizanic.sandbox.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T12:35:27.998+02:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloService",
                      portName = "HelloPortTypeBindingPort",
                      targetNamespace = "http://ws.sandbox.jkrizanic.hr/",
                      wsdlLocation = "file:wsdl/Hello.wsdl",
                      endpointInterface = "hr.jkrizanic.sandbox.ws.HelloPortType")
                      
public class HelloPortTypeImpl implements HelloPortType {

    private static final Logger LOG = Logger.getLogger(HelloPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see hr.jkrizanic.sandbox.ws.HelloPortType#getHello(hr.jkrizanic.sandbox.ws.schema.hello.HelloRequestType  name )*
     */
    public hr.jkrizanic.sandbox.ws.schema.hello.HelloResponseType getHello(hr.jkrizanic.sandbox.ws.schema.hello.HelloRequestType name) { 
        LOG.info("Executing operation getHello");
        System.out.println(name);
        try {
            hr.jkrizanic.sandbox.ws.schema.hello.HelloResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
