
package hr.jkrizanic.sandbox.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T12:35:27.969+02:00
 * Generated source version: 2.7.5
 * 
 */
public final class HelloPortType_HelloPortTypeBindingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.sandbox.jkrizanic.hr/", "HelloService");

    private HelloPortType_HelloPortTypeBindingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
        HelloPortType port = ss.getHelloPortTypeBindingPort();  
        
        {
        System.out.println("Invoking getHello...");
        hr.jkrizanic.sandbox.ws.schema.hello.HelloRequestType _getHello_name = null;
        hr.jkrizanic.sandbox.ws.schema.hello.HelloResponseType _getHello__return = port.getHello(_getHello_name);
        System.out.println("getHello.result=" + _getHello__return);


        }

        System.exit(0);
    }

}
