package hr.jkrizanic.sandbox.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-02T12:35:28.015+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.sandbox.jkrizanic.hr/", name = "HelloPortType")
@XmlSeeAlso({hr.jkrizanic.sandbox.ws.schema.hello.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPortType {

    @WebResult(name = "HelloResponseElement", targetNamespace = "http://ws.sandbox.jkrizanic.hr/schema/Hello/", partName = "helloMsg")
    @WebMethod
    public hr.jkrizanic.sandbox.ws.schema.hello.HelloResponseType getHello(
        @WebParam(partName = "name", name = "HelloRequestElement", targetNamespace = "http://ws.sandbox.jkrizanic.hr/schema/Hello/")
        hr.jkrizanic.sandbox.ws.schema.hello.HelloRequestType name
    );
}
